name: Audio Service Test
on: 
  pull_request:
    branches:
      - workflows
    types: 
      - opened
      - synchronize
permissions:
  contents: write
  pull-requests: write
env:
  WORKING_DIR: src/backend-self-hosted/docker/service/audio
jobs:
  audio_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: Set up Golang
        uses: actions/setup-go@4
        with:
          go-version: '1.25.5'
          cache-dependency-path: "$WORKING_DIR/go.sum"

      - name: Sync go.mod & go.sum
        working-directory: "$WORKING_DIR"
        run: go mod tidy

      - name: Run test + Coverage
        working-directory: "$WORKING_DIR"
        run: go test -v -covertprofile=coverage.out ./...

      - name: Show Coverage result
        working-directory: "$WORKING_DIR"
        run: go tool cover -func=coverage.out

      - name: Upload Coverage
        uses: actions/upload-artifect@4
        with:
          name: coverage-report
          path: "$WORKING_DIR"


